homeassistant:
  # Name of the location where Home Assistant is running
  name: Home
  # Location required to calculate the time the sun rises and sets
  latitude: !secret latitude
  longitude: !secret longitude
  # Impacts weather/sunrise data (altitude above sea level in meters)
  elevation: 160.2
  # metric for Metric, imperial for Imperial
  unit_system: imperial
  # Pick yours from here: http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
  time_zone: CST6CDT
  # Customization file
  customize: !include customize.yaml

# Show links to resources in log and frontend
# introduction:

# Enables the frontend
frontend:

# Enables configuration UI
config:

# Uncomment this if you are using SSL/TLS, running in Docker container, etc.
http:
#  api_password: !secret hass_pass
  ssl_certificate: !secret ssl_cert
  ssl_key: !secret ssl_key
  base_url: !secret base_url

#http: Don't use this!  Use dehydrated -- see splitbrain.org url in Google bookmarks
#  api_password: YOUR_PASSWORD
#  ssl_certificate: /etc/letsencrypt/live/txwindsurfer.duckdns.org/fullchain.pem
#  ssl_key: /etc/letsencrypt/live/txwindsurfer.duckdns.org/privkey.pem
#  base_url: txwindsurfer.duckdns.org
  
#duckdns:
#  domain: txwindsurfer
#  access_token: !secret duck_token
  
# Checks for available updates
# Note: This component will send some information about your system to
# the developers to assist with development of Home Assistant.
# For more information, please see:
# https://home-assistant.io/blog/2016/10/25/explaining-the-updater/
updater:
  # Optional, allows Home Assistant developers to focus on popular components.
  include_used_components: true

# Discover some devices automatically
discovery:
#  ignore:
#    - samsung_tv
#    - google_cast
#    - harmony
#    - cover

# Allows you to issue voice commands from the frontend in enabled browsers
conversation:

# Enables support for tracking state changes over time
history:

# View all events in a logbook
logbook:

# Enables a map showing the location of tracked devices
map:

# Track the sun
sun:

# Text to speech
tts:
  - platform: google

# Cloud
cloud:

panel_iframe:
  configurator:
    title: Configurator
    icon: mdi:wrench
    url: !secret config_url

camera:
  - platform: foscam
    ip: 192.168.1.81
    port: 88
    username: !secret camera_uname
    password: !secret foscam_pass

lutron:
  host: 192.168.1.202
  username: !secret lutron_uname
  password: !secret lutron_pass
  
mqtt:
  broker: localhost
  port: 1883
  protocol: 3.1
  keepalive: 60
  discovery: true
  discovery_prefix: smartthings
#  client_id: smartthings_x2 must be unique.  default is random
  username: !secret smartthings_mqtt_uname
  password: !secret smartthings_mqtt_pass

device_tracker:
  - platform: mqtt
    devices:
      glendasphone: "smartthings/Glenda Ramsower's Note9/presence"
      reagansphone: "smartthings/Reagan Ramsower's Note8/presence"

# enabling netgear will provide entities for devices connect to router
#  - platform: netgear
#    host: 192.168.1.1
#    username: !secret netgear_uname
#    password: !secret netgear_pass
 
lock:
  - platform: mqtt
    name: Breezeway Lock
    command_topic:  'smartthings/Breezeway Lock/lock'
    state_topic: 'smartthings/Breezeway Lock/lock'
    payload_lock: "locked"
    payload_unlock: "unlocked"
  - platform: mqtt
    name: Garage Lock
    command_topic:  'smartthings/Garage Lock/lock'
    state_topic: 'smartthings/Garage Lock/lock'
    payload_lock: "locked"
    payload_unlock: "unlocked"

# ACP will send an arm (strobe) but can't recognize ST alarm states
# alarm_control_panel:
#  - platform: mqtt
#    state_topic: "smartthings/Home Alarm/alarm"
#    command_topic: "smartthings/Home Alarm/alarm"
#    payload_arm_home: strobe
#    payload_arm_away: strobe
#    payload_disarm: off
#    retain: true

group: !include groups.yaml

# automation: !include automations.yaml

script: !include scripts.yaml

switch: !include switch.yaml

light: !include light.yaml

sensor: !include sensor.yaml

climate: !include climate.yaml

#scene:

#cover:
# - platform: lutron
 
cast:
  media_player:
  - host: 192.168.1.45
  - host: 192.168.1.48
#  - host: 192.168.1.44 Studio TV goes off
  - host: 192.168.1.47
  - host: 192.168.1.70
  - host: 192.168.1.33
#  - host: 192.168.1.41 LR TV goes off
  - host: 192.168.1.74
  - host: 192.168.1.50
  - host: 192.168.1.32
  - host: 192.168.1.40
  
logger:
  default: warning
#  logs:
#    pylutron: debug
#    pylutron.discovery: debut
#    homeassistant.components.cast.media_player: debug
#    pychromecast: debug
#    pychromecast.discovery: debug
#    pychromecast.socket_client: debug
#    zeroconf: debug

system_health:
