# Weater prediction
- platform: yr
# smartthings sensors
- platform: mqtt
  name: "Entry Sensor"
  state_topic: "smartthings/Entry Sensor/motion"
- platform: mqtt
  name: "Loggia Sensor"
  state_topic: "smartthings/Loggia Sensor/motion"
- platform: mqtt
  name: "Gameroom Motion"
  state_topic: "smartthings/Gameroom Motion/motion"
- platform: mqtt
  name: "Breezeway Door"
  state_topic: "smartthings/Zone Breezeway Door/contact"
- platform: mqtt
  name: "Utility Loggia Door"
  state_topic: "smartthings/Zone Patio Util Door/contact"
- platform: mqtt
  name: "Den Loggia Door"
  state_topic: "smartthings/Zone Patio LivRm Doo/contact"
- platform: mqtt
  name: "Den Back Door"
  state_topic: "smartthings/Zone Livingroom Back Door/contact"
